### ISSUE TITLE
Zero Percent

### ISSUE THREAD

**Issue by Yousra-Regaya** [pie-meister/pie-meister.github.io#1]
Hi,
By default, the zero percent in the progress-circle is converted into 100%.
I want to change that and keep the percent appearing as it is.
I tried to change the code but with no hope.
Kindly advise.

**Comment by Danny-Engelman** [comment]
Sorry, its as I said in the documenation:

| This is UNlicensed source code; a STARTING POINT for your own Web Components

I will not fix bugs
